# Generated by Django 4.1.3 on 2022-11-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=8)),
            ],
        ),
    ]
