# Generated by Django 4.1.3 on 2022-11-08 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tamaño', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCarne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCarme', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hamburguesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tamaño', models.CharField(max_length=20)),
                ('numeroCarne', models.CharField(max_length=20)),
                ('vegetales', models.CharField(max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.sucursal')),
                ('tipoCarme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.tipocarne')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellio', models.CharField(max_length=30)),
                ('puesto', models.CharField(max_length=30)),
                ('horario', models.TimeField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Combos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('Sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.sucursal')),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.bebidas')),
                ('hamburguesas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.hamburguesas')),
            ],
        ),
        migrations.AddField(
            model_name='bebidas',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.proveedor'),
        ),
        migrations.AddField(
            model_name='bebidas',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.sucursal'),
        ),
    ]
