# Generated by Django 4.1.3 on 2022-11-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_bebidas_proveedor_tipocarne_hamburguesas_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
