# Generated by Django 4.1.3 on 2022-11-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_sucursal_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='horario',
        ),
    ]
