# Generated by Django 4.1.3 on 2022-11-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_remove_empleado_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='horario',
            field=models.TimeField(null=True),
        ),
    ]
